### ISSUE TITLE
VST.msl.msl_direct

### ISSUE THREAD

**Issue by andrew-appel** [CertiGraph/CertiGraph#17]
CertiGraph ought to be able to build in the standard Coq Platform installation of VST.  Right now, that build of VST does not include the file VST.msl.msl_direct.  That msl_direct is still in the VST repo, but it is not in the opam-build configuration.

For now I will try disabling such files as CertiGraph/msl_ext/overlapping_direct.v form the makefile.  But if msl/msl_direct is important to CertiGraph, then I suggest you file a VST issue report requesting that msl_direct be added to the make targets in VST/util/calc_install_files

**Comment by txyyss** [comment]
`msl_direct` is not required in the default branch now.
