### ISSUE TITLE
Build Error : Can't find variable H19 in CertiGC

### ISSUE THREAD

**Issue by ahmedshakill** [CertiGraph/CertiGraph#23]
I was trying to build CertiGraph. But build fails with the following 

File ".//CertiGC/verif_forward1.v", line 164, characters 74-77:
Error: The variable H19 was not found in the current environment.

I am on the latest commit 786e7ed1172b9025990cd849077e7103b8c64e47 
of  branch "live"

**Comment by txyyss** [comment]
Could you please tell me the version of Coq you are using to build CertiGraph?

**Comment by ahmedshakill** [comment]
Later I ran the command "opam install --deps-only . " in the project directory to install required versions. 
Now I am using Coq version 8.16.1.
The previous error is gone  and now getting this one.

File ".//binheap/verif_binary_heap.v", line 361, characters 99-104:
Error: Tactic failure: Classical tauto failed.

**Comment by txyyss** [comment]
Some examples in the CertiGraph project are outdated in new versions of Coq or VST. You can run `make -k` to ignore the uncompilable examples. At least the core formalization part of graph theory and the verification of the garbage collector still work.

We may fix the build error problem later.

**Comment by ahmedshakill** [comment]
This time with `make -k` build finished . 
Maybe irrelevant but 
How is VSCoq ? What's your setup for Coq? CoqIDE, Proof General or VSCoq ?

**Comment by txyyss** [comment]
I'm using Proof General.

**Comment by ahmedshakill** [comment]
Thanks a lot.
